publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/articles'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'

    fields:
      - { label: 'タイトル', name: 'title', widget: 'string', required: true }
      - {
          label: '詳細',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: '本文', name: 'body', widget: 'markdown', required: false }
  - name: 'Member'
    label: 'メンバー'
    folder: 'content/members'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'

    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - {
          label: 'アイコン',
          name: 'icon',
          widget: 'file',
          default: '/images/inarizushi.jpg',
        }
      - { label: '紹介', name: 'text', widget: 'string', required: false }
